// Galaxy data — real astronomical information
// Each galaxy: name, description, visual theme, difficulty scaling

const GALAXIES = [
  {
    id: 1,
    name: '太阳系',
    nameEn: 'Solar System',
    stars: 1,
    planets: 8,
    description: '我们的家园。太阳系由一颗中等大小的恒星——太阳，以及围绕它运行的8颗行星、众多卫星、小行星和彗星组成。位于银河系猎户座旋臂内侧，距银心约2.6万光年。目前只有地球已知存在生命。',
    funFact: '太阳包含了太阳系99.86%的质量！',
    spinSpeed: 0.6,
    orbitRadius: 110,
    difficulty: 1,
    color: '#FFD700',
    spiralArms: 3,
    starsCount: 40,
  },
  {
    id: 2,
    name: '半人马座α',
    nameEn: 'Alpha Centauri',
    stars: 3,
    planets: 5,
    description: '距离太阳系最近的恒星系统，仅4.37光年。由三颗恒星组成：比邻星（Proxima Centauri）、南门二A和南门二B。比邻星周围已发现多颗行星，其中比邻星b位于宜居带内。',
    funFact: '比邻星是一颗红矮星，寿命可达数万亿年，远超宇宙当前年龄！',
    spinSpeed: 0.8,
    orbitRadius: 115,
    difficulty: 2,
    color: '#FF6B35',
    spiralArms: 3,
    starsCount: 50,
  },
  {
    id: 3,
    name: '天狼星',
    nameEn: 'Sirius',
    stars: 2,
    planets: 0,
    description: '夜空中最亮的恒星，位于大犬座，距地球约8.6光年。天狼星实际上是一个双星系统：明亮的天狼星A和一颗白矮星伴星天狼星B。在古代文明中，天狼星具有重要的文化和天文意义。',
    funFact: '古埃及人根据天狼星的升起时间预测尼罗河的年度洪水！',
    spinSpeed: 0.9,
    orbitRadius: 118,
    difficulty: 2,
    color: '#87CEEB',
    spiralArms: 3,
    starsCount: 60,
  },
  {
    id: 4,
    name: '仙女座星系',
    nameEn: 'Andromeda Galaxy',
    stars: 1000000000000,
    planets: '未知（估计数十亿）',
    description: '距我们约250万光年，是离银河系最近的大型螺旋星系，也是本星系群中最大的星系。仙女座星系包含约1万亿颗恒星，是银河系的2-3倍。它正以每秒约110公里的速度靠近银河系，预计在45亿年后与银河系相撞合并。',
    funFact: '仙女座星系是肉眼可见的最远天体——在无光污染的地方，你可以直接用肉眼看到它！',
    spinSpeed: 1.1,
    orbitRadius: 125,
    difficulty: 4,
    color: '#9B59B6',
    spiralArms: 5,
    starsCount: 90,
  },
  {
    id: 5,
    name: '猎户座星云',
    nameEn: 'Orion Nebula',
    stars: '约700（形成中）',
    planets: '多个原行星盘',
    description: '位于猎户座"宝剑"位置，距地球约1,344光年，是离我们最近的恒星形成区之一。猎户座星云是一个巨大的气体和尘埃云，正在孕育数百颗新恒星。哈勃望远镜在这里拍摄到了许多壮观的"原行星盘"。',
    funFact: '猎户座星云中的气体如果聚集起来，可以形成约10,000个太阳质量的新恒星！',
    spinSpeed: 1.2,
    orbitRadius: 120,
    difficulty: 3,
    color: '#E91E63',
    spiralArms: 4,
    starsCount: 100,
  },
  {
    id: 6,
    name: '昴星团',
    nameEn: 'Pleiades (M45)',
    stars: '约1,000',
    planets: 0,
    description: '又称"七姐妹星团"，位于金牛座，距地球约444光年。这是一个年轻的疏散星团，由约1,000颗恒星组成，年龄仅约1亿年。昴星团在几乎每一种人类文化中都有记载，从希腊神话到日本"Subaru"品牌。',
    funFact: '昴星团中的蓝色反射星云最初被认为是残留的星云物质，后来发现只是星际尘埃云恰好经过星团附近！',
    spinSpeed: 1.0,
    orbitRadius: 122,
    difficulty: 3,
    color: '#4488FF',
    spiralArms: 4,
    starsCount: 80,
  },
  {
    id: 7,
    name: '大麦哲伦云',
    nameEn: 'Large Magellanic Cloud',
    stars: '约300亿',
    planets: '未知',
    description: '银河系最大的卫星星系，距我们约16.3万光年。它是一个不规则矮星系，正在被银河系的引力缓慢撕裂。1987年，超新星SN 1987A在此爆发，是天文学史上最重要的事件之一。这里也是恒星形成的活跃区域。',
    funFact: '大麦哲伦云是南半球肉眼可见的"云雾状"天体——16世纪麦哲伦环球航行时首次被欧洲人详细记录！',
    spinSpeed: 1.3,
    orbitRadius: 128,
    difficulty: 5,
    color: '#00BCD4',
    spiralArms: 2,
    starsCount: 110,
  },
  {
    id: 8,
    name: '草帽星系',
    nameEn: 'Sombrero Galaxy (M104)',
    stars: '约1,000亿',
    planets: '未知',
    description: '位于室女座，距地球约2,800万光年。因其独特的外观——明亮的核球和黑暗的尘埃带，像一顶墨西哥草帽而得名。这可能是两个星系合并后的产物，拥有一个超大质量黑洞（约10亿倍太阳质量）。',
    funFact: '草帽星系的尘埃环是它的标志性特征，这个环包含了星系中大部分冷气体和尘埃，也是恒星形成的主要场所！',
    spinSpeed: 1.4,
    orbitRadius: 132,
    difficulty: 6,
    color: '#F5F5DC',
    spiralArms: 4,
    starsCount: 120,
  },
  {
    id: 9,
    name: '涡状星系',
    nameEn: 'Whirlpool Galaxy (M51)',
    stars: '约1,600亿',
    planets: '未知',
    description: '位于猎犬座，距地球约2,300万光年。涡状星系是第一个被分类为螺旋星系的星系，以其优美的螺旋结构闻名。它与伴星系NGC 5195正在发生引力相互作用，这种相互作用实际上增强了它的螺旋结构。',
    funFact: '涡状星系的螺旋结构如此完美，以至于天文学家Lord Rosse在1845年首次绘制它时，称其为"夜空中的问号"！',
    spinSpeed: 1.5,
    orbitRadius: 135,
    difficulty: 7,
    color: '#7C4DFF',
    spiralArms: 5,
    starsCount: 130,
  },
  {
    id: 10,
    name: '车轮星系',
    nameEn: 'Cartwheel Galaxy',
    stars: '约500亿',
    planets: '未知',
    description: '位于玉夫座，距地球约5亿光年。车轮星系因其独特的外观得名：一个明亮的核心、一个几乎空无一物的间隙和一个发光的蓝色外环——就像车轮的辐条。这种结构是约2亿年前一个小星系高速穿过它的中心造成的，产生了向外传播的恒星形成波。',
    funFact: '车轮星系的外环直径约15万光年（比银河系还大），且正在以每小时数百万公里的速度向外扩张！',
    spinSpeed: 1.7,
    orbitRadius: 140,
    difficulty: 8,
    color: '#FF4081',
    spiralArms: 2,
    starsCount: 100,
  },
];

export function getGalaxy(index) {
  if (index >= GALAXIES.length) return GALAXIES[GALAXIES.length - 1];
  if (index < 0) return GALAXIES[0];
  return GALAXIES[index];
}

export function getGalaxyCount() {
  return GALAXIES.length;
}

export default GALAXIES;
